#!/usr/bin/env python3
"""Keep the agent leaderboard: add an agent's pilot results and re-render the tables.

Examples:
    # add one agent from a run folder (its pilot cases), then re-render
    python scripts/leaderboard.py add results/runs/pilot --agent codex \\
        --name Codex --model GPT-5.4 --interface "Coding agent (CLI)"

    # re-render README.md and docs/leaderboard.md from leaderboard/entries.json
    python scripts/leaderboard.py render
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from tickmark.leaderboard import (  # noqa: E402
    entry_from_records,
    load_entries,
    ranked,
    replace_between,
    save_entries,
    table,
    upsert,
)

ENTRIES = ROOT / "leaderboard" / "entries.json"
README = ROOT / "README.md"
DOC = ROOT / "docs" / "leaderboard.md"


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    commands = parser.add_subparsers(dest="command", required=True)
    add = commands.add_parser("add", help="add or update one agent from a run folder")
    add.add_argument("run_dir", type=Path, help="results/runs/<run-id>")
    add.add_argument("--agent", required=True, help="agent folder name inside the run")
    add.add_argument("--name", required=True, help="agent or product name, e.g. Codex")
    add.add_argument("--model", default="", help="model name, e.g. GLM-5.2")
    add.add_argument("--interface", required=True, help='e.g. "Coding agent (CLI)"')
    add.add_argument("--note", default="", help="optional note shown under the table")
    commands.add_parser("render", help="re-render README.md and docs/leaderboard.md")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    data = load_entries(ENTRIES)
    if args.command == "add":
        summary = json.loads((args.run_dir / "summary.json").read_text(encoding="utf-8"))
        try:
            stats = entry_from_records(summary["records"], args.agent, data["cases"])
        except ValueError as error:
            print(error, file=sys.stderr)
            return 2
        entry = {
            "name": args.name,
            "model": args.model,
            "interface": args.interface,
            **stats,
            "engine": summary.get("engine", ""),
            "date": (summary.get("written_at") or date.today().isoformat())[:10],
            "run": args.run_dir.name,
            "note": args.note,
        }
        data["entries"] = upsert(data["entries"], entry)
        save_entries(ENTRIES, data)
        print(f"{args.name}: {stats['real_models']}/{stats['cases']} real models")
    render(data)
    print(table(data["entries"]))
    return 0


def render(data: dict) -> None:
    rows = table(data["entries"])
    README.write_text(replace_between(README.read_text(encoding="utf-8"), rows), encoding="utf-8")
    DOC.write_text(_document(data, rows), encoding="utf-8")


def _document(data: dict, rows: str) -> str:
    details = [
        "| Agent | Model | Value correctness | Engine | Date | Run |",
        "|---|---|---:|---|---|---|",
    ]
    for e in ranked(data["entries"]):
        details.append(
            f"| {e['name']} | {e.get('model') or '–'} | {100 * e['value_correctness']:.0f}% | "
            f"{e['engine']} | {e['date']} | `{e['run']}` |"
        )
    notes = [
        f"- **{e['name']}{' · ' + e['model'] if e.get('model') else ''}**: {e['note']}"
        for e in ranked(data["entries"])
        if e.get("note")
    ]
    cases = ", ".join(f"`{case}`" for case in data["cases"])
    return f"""# Agent leaderboard

Agents graded on the same pilot cases ({cases}): a revenue projection, a working-capital
forecast and a rent roll. Generated by `scripts/leaderboard.py` from
[`leaderboard/entries.json`](../leaderboard/entries.json); do not edit the tables by hand.

- **Real models**: cases passed, meaning every number right and every audit check passed.
- **Right numbers**: cases with every number right, which is all a value-only benchmark checks.
- **Formulas** and **Traceable**: mean share of target cells that hold formulas, and that trace
  back to the declared inputs.

{rows}

{chr(10).join(details)}

{chr(10).join(notes)}

## Add an agent

1. Run the pilot, for any configured agent or any `<provider>:<model>`
   ([docs/agents.md](agents.md)):

   ```bash
   uv run python scripts/run_real_agent_suite.py --agents openrouter:<model-id> --run-id my-agent
   ```

2. Add it and re-render the tables:

   ```bash
   uv run python scripts/leaderboard.py add results/runs/my-agent --agent <folder> \\
       --name "<Agent>" --model "<Model>" --interface "Chat API (OpenRouter)"
   ```

   `<folder>` is the agent's folder inside the run, for example
   `openrouter-z-ai-glm-5.2-free`.

3. Open a pull request with `leaderboard/entries.json`, `README.md` and
   `docs/leaderboard.md`.
"""


if __name__ == "__main__":
    raise SystemExit(main())
