#!/usr/bin/env python3
"""Keep the agent leaderboard: add an agent's pilot results and re-render it.

Examples:
    # add one agent from a run folder (its pilot cases), then re-render
    python scripts/leaderboard.py add results/runs/pilot --agent codex \\
        --name Codex --model GPT-5.4 --interface "Coding agent · Codex CLI"

    # re-render assets/leaderboard.svg, README.md and docs/leaderboard.md
    python scripts/leaderboard.py render
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from tickmark.leaderboard import (  # noqa: E402
    entry_from_records,
    label,
    load_entries,
    ranked,
    replace_between,
    save_entries,
    svg_card,
    table,
    upsert,
)

ENTRIES = ROOT / "leaderboard" / "entries.json"
CARD = ROOT / "assets" / "leaderboard.svg"
README = ROOT / "README.md"
DOC = ROOT / "docs" / "leaderboard.md"


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    commands = parser.add_subparsers(dest="command", required=True)
    add = commands.add_parser("add", help="add or update one agent from a run folder")
    add.add_argument("run_dir", type=Path, help="results/runs/<run-id>")
    add.add_argument("--agent", required=True, help="agent folder name inside the run")
    add.add_argument("--name", required=True, help="agent or product name, e.g. Codex")
    add.add_argument("--model", default="", help="model name, e.g. GLM-5.2")
    add.add_argument("--interface", required=True, help='e.g. "Coding agent · Codex CLI"')
    add.add_argument("--note", default="", help="optional note shown under the table")
    commands.add_parser("render", help="re-render the card, README.md and docs/leaderboard.md")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    data = load_entries(ENTRIES)
    if args.command == "add":
        summary = json.loads((args.run_dir / "summary.json").read_text(encoding="utf-8"))
        try:
            stats = entry_from_records(summary["records"], args.agent, data["cases"])
        except ValueError as error:
            print(error, file=sys.stderr)
            return 2
        entry = {
            "name": args.name,
            "model": args.model,
            "interface": args.interface,
            **stats,
            "engine": summary.get("engine", ""),
            "date": (summary.get("written_at") or date.today().isoformat())[:10],
            "run": args.run_dir.name,
            "note": args.note,
        }
        data["entries"] = upsert(data["entries"], entry)
        save_entries(ENTRIES, data)
        print(f"{args.name}: {stats['real_models']}/{stats['cases']} real models")
    render(data)
    print(table(data["entries"]))
    return 0


def render(data: dict) -> None:
    updated = max(e["date"] for e in data["entries"])
    CARD.write_text(svg_card(data["entries"], data["cases"], updated), encoding="utf-8")
    rows = table(data["entries"])
    top = ", ".join(
        f"{label(e)} {e['real_models']}/{e['cases']}" for e in ranked(data["entries"])[:3]
    )
    block = (
        f'<p align="center"><img src="assets/leaderboard.svg" width="100%" '
        f'alt="Tickmark leaderboard, real models on the pilot cases: {top}. '
        f'Full table below."></p>\n\n'
        f"<details>\n<summary>Table view</summary>\n\n{rows}\n\n</details>"
    )
    README.write_text(replace_between(README.read_text(encoding="utf-8"), block), encoding="utf-8")
    DOC.write_text(_document(data, rows), encoding="utf-8")


def _document(data: dict, rows: str) -> str:
    details = [
        "| Agent | Engine | Date | Run |",
        "|---|---|---|---|",
    ]
    for e in ranked(data["entries"]):
        details.append(f"| {label(e)} | {e['engine']} | {e['date']} | `{e['run']}` |")
    notes = [f"- **{label(e)}**: {e['note']}" for e in ranked(data["entries"]) if e.get("note")]
    cases = ", ".join(f"`{case}`" for case in data["cases"])
    return f"""# Agent leaderboard

Agents graded on the same pilot cases ({cases}): a revenue projection, a working-capital
forecast and a rent roll. Generated by `scripts/leaderboard.py` from
[`leaderboard/entries.json`](../leaderboard/entries.json); do not edit the tables by hand.

<p align="center"><img src="../assets/leaderboard.svg" width="100%" alt="Leaderboard card"></p>

- **Real models**: cases passed, meaning every number right and every audit check passed.
- **Right numbers**: cases with every number right, which is all a value-only benchmark
  checks.
- **Checks passed**: share of all audit checks passed across the cases (7 per case, equal
  weight).
- **Values right**, **Formulas**, **Traceable**: mean share of target cells with the right
  value, holding a formula, and tracing back to the declared inputs.
- **Time per case**: median wall-clock seconds per case. On free tiers this includes
  provider queueing and rate-limit waits, so compare speed with care.

Ranked by real models, then checks passed, then right numbers; agents equal on all three
share a rank.

{rows}

{chr(10).join(details)}

{chr(10).join(notes)}

## Add an agent

1. Run the pilot, for any configured agent or any `<provider>:<model>`
   ([docs/agents.md](agents.md)):

   ```bash
   uv run python scripts/run_real_agent_suite.py --agents openrouter:<model-id> --run-id my-agent
   ```

2. Add it and re-render the card and tables:

   ```bash
   uv run python scripts/leaderboard.py add results/runs/my-agent --agent <folder> \\
       --name "<Agent>" --model "<Model>" --interface "Chat API · OpenRouter"
   ```

   `<folder>` is the agent's folder inside the run, for example
   `openrouter-z-ai-glm-5.2-free`.

3. Open a pull request with `leaderboard/entries.json`, `assets/leaderboard.svg`,
   `README.md` and `docs/leaderboard.md`.
"""


if __name__ == "__main__":
    raise SystemExit(main())
